pipeline {
    agent any

    environment {
        IMAGE = "chico871/flask-ben"
        TAG   = "latest"
        KUBECONFIG = "/root/.kube/config"
        MINIKUBE_HOME = "/root"
    }

    stages {
        stage('build') {
            steps {
                sh 'docker build -t $IMAGE:$TAG Phase1/Flask_Bens'
            }
        }

        stage('test') {
            steps {
                sh 'kubectl rollout status deployment/flask-ben --timeout=60s'
                script {
                    def ip = sh(
                        script: 'minikube ip',
                        returnStdout: true
                    ).trim()
                    sh "curl -f http://${ip}:30000"
                }
            }
        }

        stage('deploy') {
            steps {
                sh 'docker push $IMAGE:$TAG'
            }
        }
    }
}
